### PR TITLE
Rename forked packages for publishing on pub

### LINKED ISSUE #7: New library names to publish forked by AngularDart Community packages
This task is a part of [AngularDart 8 Roadmap](https://github.com/angulardart-community/angular/issues/6) 

Rename forked by AngularDart Community packages to be able publish and use them on pub.dev

New package names:
angular -> ngdart (the existing ngdart package utility will be renamed to ngdart_cli)
angular_ast  -> ngast
angular_compiler -> ngcompiler
angular_forms -> ngforms
angular_router -> ngrouter
angular_test -> ngtest

Dart SDK: 2.17.0
AngularDart Version: 8.0.0

### PR DESCRIPTION
**Pull request by IgorBabalich**
Fixes #7, #5.

Renaming forked by AngularDart Community packages to be able publish and use them on pub.dev
Resolving builds and tests. Fix complained test analyzis. 
New package names:
   angular -> ngdart (the existing ngdart package utility will be renamed to ngdart_cli)
   angular_ast -> ngast
   angular_compiler -> ngcompiler
   angular_forms -> ngforms
   angular_router -> ngrouter
   angular_test -> ngtest

### CODE REVIEW

**Comment by GZGavinZhao** [comment]
@IgorBabalich CI enabled. Please check the errors and fix them accordingly. I think many of them can be resolved by a top-level `dart format`.

**Comment by IgorBabalich** [comment]
Fixed formatting.

**Review by GZGavinZhao — CHANGES_REQUESTED** [review]
Please rename directories (e.g. `angular` to `ngdart`, `angular_forms` to `ngforms`).

**Comment by IgorBabalich** [comment]
Renamed package directories

**Comment by GZGavinZhao** [comment]
@IgorBabalich Please regenerate CI config using `mono_repo generate`: https://pub.dev/packages/mono_repo

**Comment by IgorBabalich** [comment]
mono_repo re-generated

**Comment by GZGavinZhao** [comment]
Looks good to me. Thanks!

**Pull request merged**
