### PR TITLE
refactor(ngcompiler): fix all static warnings.

### PR DESCRIPTION
**Pull request by ykmnkmi**

### CODE REVIEW

**Comment by denniskaselow** [comment]
Because I found those fails interesting, I took a look at it. The tests use intl 0.18.1 which was published yesterday and and one of the changes was this:

https://github.com/dart-lang/i18n/blame/468f08c6a08b81879e769f80c4a6f7b0d763e4a1/pkgs/intl/test/date_time_strict_test.dart#L52

Instead of a normal whitespace it's now a `\u202F` or Narrow No-Break Space (NNBSP).

**Comment by ykmnkmi** [comment]
@denniskaselow thank you.

**Comment by GZGavinZhao** [comment]
> @GZGavinZhao, I don't think it's breaking PR, as it's not a _public_ package. Strange fails, could they be related to Chrome?

I agree that this doesn't need to be a breaking change. Also thank you @denniskaselow for investigating the issue!

**Review by GZGavinZhao — APPROVED** [review]
Looks good to me. Thank you for your work!

**Pull request merged**
