### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by ykmnkmi**

### CODE REVIEW

**Comment by GZGavinZhao** [comment]
Should the lower bound of the SDK stay at 3.0.0 instead of 3.1.0 for maximum compatibility?

**Comment by ykmnkmi** [comment]
@GZGavinZhao `mockito` `5.4.3` which requires Dart SDK version `^3.1.0`.

**Comment by GZGavinZhao** [comment]
Oh yes, you're right. Well, that's sad, we have to keep the min SDK bound at 3.1.0 then.

**Comment by ykmnkmi** [comment]
Dart 3.2 is already released. `_tests/test` is not updated. I also noticed old doc. comments to update.

**Comment by GZGavinZhao** [comment]
I think we should keep min SDK bound to 3.1 unless there are packages/language features that prevents us from doing so.

Regarding `_tests/test`, locally I was able to migrate all files to Dart 3 except 3:
- `_tests/test/core/linker/security_integration_test.dart`
- `_tests/test/compiler/output/dart_emitter_test.dart`
- `_tests/test/compiler/ast_directive_normalizer_test.dart`

I'm not sure how I should merge the changes with yours. Do you want me to push to your existing working branch directly?

**Comment by ykmnkmi** [comment]
Some tests show that mock-like behavior is not supported in null-safety mode:
```dart
group('should be mock-like', () {
  mockLikeTests(nullSafe: false);
});

group('should never be mock-like when opted-in to null-safety', () {
  mockLikeTests(nullSafe: true);
});
```
Maybe remove all mock-like tests? I try to disable the null-safety option in the compile context.

**Comment by ykmnkmi** [comment]
Found this:
```dart
/// Whether this output has mock-like behavior.
///
/// The heuristic used to determine mock-like behavior is if the analyzed
/// class or one of its ancestors, other than [Object], implements
/// [noSuchMethod].
///
/// Note that is the value is _never_ true for null-safe libraries, as we no
/// longer support null streams/stream subscriptions in the generated code.
```

**Comment by GZGavinZhao** [comment]
I think this is ready for merge?

**Comment by ykmnkmi** [comment]
@GZGavinZhao yes.

**Review by GZGavinZhao — APPROVED** [review]

**Pull request merged**
