### PR TITLE
refactor!: fixing all static analysis warnings

### PR DESCRIPTION
**Pull request by ykmnkmi**

### CODE REVIEW

**Comment by ykmnkmi** [comment]
@GZGavinZhao I think we need to bump the minimal SDK version to `2.18.0`.

**Comment by GZGavinZhao** [comment]
@ykmnkmi I'm okay with it. You also might need to lock `build_modules` to `^4.0.7`

**Comment by GZGavinZhao** [comment]
Oh also, if you would like to [sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) when your PR is ready that would be great. So far I've been manually squashing the commits and signing them using my keys (which is why you sometimes see commits are authored by you but committed by me), and I'm happy to keep doing so, but if it's convenient for you to sign them then that would be great :)

**Comment by ykmnkmi** [comment]
@GZGavinZhao thanks for helping with commits and PR's.

**Pull request closed without merging**
