### PR TITLE
feat: migrate to package:web

### PR DESCRIPTION
**Pull request by ahmednfwela**

### CODE REVIEW

**Comment by ahmednfwela** [comment]
There are some blocking issues right now: 
- https://github.com/dart-lang/web/issues/252#issuecomment-2160022045

**Comment by GZGavinZhao** [comment]
@ahmednfwela Thanks for starting this effort! Mind if I push commits on top of yours directly?

**Comment by ahmednfwela** [comment]
sure, please go ahead!

**Comment by GZGavinZhao** [comment]
@ahmednfwela Can you enable allow "edits to maintainers" as shown [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by ahmednfwela** [comment]
since to allow maintainers to edit, the source branch needs to be on a personal account (not an org account), I will recreate the PR.

**Comment by ahmednfwela** [comment]
new PR: https://github.com/angulardart-community/angular/pull/75

**Pull request closed without merging**
