### PR TITLE
refactor(ngdart)!: rename and remove deprecated fields from ChangeDetectionStrategy

### PR DESCRIPTION
**Pull request by ykmnkmi**

### CODE REVIEW

**Comment by GZGavinZhao** [comment]
You may want to submit the enum migrations one by one if doing it all together is too much.

**Comment by ykmnkmi** [comment]
Do you mean `ViewEncapsulation`?

**Comment by GZGavinZhao** [comment]
Yes.

**Review by GZGavinZhao — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
