### PR TITLE
Dart 2.17 enums refactoring

### LINKED ISSUE #12: Refactor to use Dart-2.17 new enum features
Search, review and refactor to use Dart-2.17 new enum features where possible

Dart SDK: 2.17.0

### PR DESCRIPTION
**Pull request by IgorBabalich**
Fixes #12.

Refactor const lists to enums with values, fixing tests analyzer complains.

### CODE REVIEW

**Comment by GZGavinZhao** [comment]
Nice work! Feel free to request my review so I know you're finished :)

**Comment by IgorBabalich** [comment]
Hi @GZGavinZhao  
I finished with this 'angular' repo pull request. How to request your review, please? If there is a some button to click? Or just informal request in comments?

**Review by GZGavinZhao — APPROVED** [review]
Looks good to me. Thanks!

**Comment by GZGavinZhao** [comment]
@IgorBabalich You can request a review like this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review

**Comment by IgorBabalich** [comment]
Thank you @GZGavinZhao 

Looks like I don't have this feature to request a review due to the Note on provided page:

> Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

**Pull request merged**
